export const PRODUCT_DETAIL_SUCCESS="PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL="PRODUCT_DETAIL_FAIL"
export const PRODUCT_DETAIL_REQUEST="PRODUCT_DETAIL_REQUEST"

export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL"



export const PRODUCT_CREATE_REVIEWS_REQUEST="PRODUCT_CREATE_REVIEWS_REQUEST"
export const PRODUCT_CREATE_REVIEWS_SUCCESS="PRODUCT_CREATE_REVIEWS_SUCCESS"
export const PRODUCT_CREATE_REVIEWS_FAIL="PRODUCT_CREATE_REVIEWS_FAIL"
export const PRODUCT_CREATE_REVIEWS_RESET="PRODUCT_CREATE_REVIEWS_FCREATE_RESET"

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'